[package]
authors = ["Samuel Keiffer <samuelkeiffer@gmail.com>"]
edition = "2021"
name = "veloren-server-agent-dyn"
version = "0.1.0"

[lib]
crate-type = ["dylib"]

[features]
be-dyn-lib = ["veloren-server-agent/be-dyn-lib"]

[dependencies]
veloren-server-agent = { path = "../" }
